In [1]:
import pandas as pd
import numpy as np

import Util

In [2]:
#import data from andd add 5a
df = pd.read_csv("./datasets/kitab-hukum-perdata/dataset_clean.csv",encoding="unicode_escape")
pasal5a = "Anak sah, dan juga anak tidak sah namun yang diakui oleh bapaknya, memakai nama keturunan bapaknya; anak-anak tidak sah yang tidak diakui oleh bapaknya, memakai nama keturunan ibunya."
pasal5b = "Anak-anak tidak sah yang tidak diakui oleh bapaknya, memakai nama keturunan ibunya."
df.loc[4.5] = ["Pasal 5a",pasal5a]
df.loc[4.6] = ["Pasal 5b",pasal5b]
df = df.sort_index().reset_index(drop = True)

## Buku tentang orang

In [3]:
pd.options.mode.copy_on_write = True

In [4]:
## memasukan identitas buku
book_1 = df.iloc[:df[df["Pasal"] == "Pasal 495"].index[0]+1]
book_1["Buku"] = 1

In [5]:
book_1.head()

     Pasal                                                Isi  Buku
0  Pasal 1  Menikmati hak-hak kewargaan tidak tergantung p...     1
1  Pasal 2  Anak yang ada dalam kandungan seorang perempua...     1
2  Pasal 3  Tiada suatu hukuman pun yang mengakibatkan kem...     1
3  Pasal 4  Tanpa mengurangi ketentuan dalam Pasal 10 Kete...     1
4  Pasal 5  Presiden, setelah mendengar Mahkamah Agung men...     1

In [6]:
## memasukan identitas Bab
book_1["Bab"] = np.nan
book_1["Bagian"] = np.nan

In [7]:
book_1

,Pasal,Isi,Buku,Bab,Bagian
0,Pasal 1,Menikmati hak-hak kewargaan tidak tergantung p...,1,NaN,NaN
1,Pasal 2,Anak yang ada dalam kandungan seorang perempua...,1,NaN,NaN
2,Pasal 3,Tiada suatu hukuman pun yang mengakibatkan kem...,1,NaN,NaN
3,Pasal 4,Tanpa mengurangi ketentuan dalam Pasal 10 Kete...,1,NaN,NaN
4,Pasal 5,"Presiden, setelah mendengar Mahkamah Agung men...",1,NaN,NaN
...,...,...,...,...,...
514,Pasal 491,Ketentuan-ketentuan dari kedua pasal yang lalu...,1,NaN,NaN
515,Pasal 492,Bila kemudian orang yang dalam keadaan tak had...,1,NaN,NaN
516,Pasal 493,"Bila salah seorang dari suami isteri, selain m...",1,NaN,NaN
517,Pasal 494,"Bila atas panggilan ketiga dari Pengadilan, ba...",1,NaN,NaN
518,Pasal 495,"Bila setelah pemberian izin, tetapi sebelum pe...",1,NaN,NaN

In [8]:
Util.insertPasalToBab(book_1,["1","3"],"MENIKMATI DAN KEHILANGAN HAK KEWARGAAN")

/home/spinx/KMIPN V/Lab/Util.py:48: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value 'MENIKMATI DAN KEHILANGAN HAK KEWARGAAN' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[df[df["Pasal"] == pasal[0]].index[0] : df[df["Pasal"] == pasal[1]].index[0],"Bab"] = bab

In [13]:
book_1

,Pasal,Isi,Buku,Bab,Bagian
0,Pasal 1,Menikmati hak-hak kewargaan tidak tergantung p...,1,MENIKMATI DAN KEHILANGAN HAK KEWARGAAN,NaN
1,Pasal 2,Anak yang ada dalam kandungan seorang perempua...,1,MENIKMATI DAN KEHILANGAN HAK KEWARGAAN,NaN
2,Pasal 3,Tiada suatu hukuman pun yang mengakibatkan kem...,1,MENIKMATI DAN KEHILANGAN HAK KEWARGAAN,NaN
3,Pasal 4,Tanpa mengurangi ketentuan dalam Pasal 10 Kete...,1,AKTA-AKTA CATATAN SIPIL,NaN
4,Pasal 5,"Presiden, setelah mendengar Mahkamah Agung men...",1,AKTA-AKTA CATATAN SIPIL,NaN
...,...,...,...,...,...
514,Pasal 491,Ketentuan-ketentuan dari kedua pasal yang lalu...,1,NaN,NaN
515,Pasal 492,Bila kemudian orang yang dalam keadaan tak had...,1,NaN,NaN
516,Pasal 493,"Bila salah seorang dari suami isteri, selain m...",1,NaN,NaN
517,Pasal 494,"Bila atas panggilan ketiga dari Pengadilan, ba...",1,NaN,NaN
518,Pasal 495,"Bila setelah pemberian izin, tetapi sebelum pe...",1,NaN,NaN

In [17]:
Util.melihatPasal(df,"Pasal 230c")

          Pasal                                                Isi
234  Pasal 230c  Bila tidak ada perintah seperti yang dimaksud ...

In [18]:
df.to_csv("./datasets/new_clean_csv.csv")